config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'contact_files#index'

  resources :contact_files
  resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :contact_list
  has_many :users, through: :contact_list

  validates :name, :birthday, :email, :phone, :address, :credit_card, :franchise, presence: true
  validates :credit_card, length: { in: 8..19 }
  validates :phone, format: { with: /[(](.+\d{2})[)]\s\d{3}(\s|-)\d{3}(\s|-)\d{2}(\s|-)\d{2}/,
                              message: 'Invalid format.' }
  validates_format_of :email, with: Devise::email_regexp
end

app/models/contact_file.rb
class ContactFile < ApplicationRecord
  belongs_to :user
  has_one_attached :csv_file

  validates :csv_file, presence: true

  enum status: {
    waiting: 'waiting',
    processing: 'processing',
    failed: 'failed',
    done: 'done'
  }
end

app/models/contact_list.rb
class ContactList < ApplicationRecord
  belongs_to :user
  belongs_to :contact
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contact_list
  has_many :contacts, through: :contact_list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_files_controller.rb
class ContactFilesController < ApplicationController
  before_action :authenticate_user!

  def index
    @contact_files = ContactFile.all
  end

  def new
    @contact_file = ContactFile.new
  end

  def create
    RegisterFileService.call(current_user, contact_file_params, mapped_values)
    redirect_to action: :index
  end

  private

  def contact_file_params
    params.require(:contact_file).permit(:csv_file)
  end

  def mapped_values
    {
      name: params[:name],
      birthday: params[:birthday],
      phone: params[:phone],
      address: params[:address],
      credit_card: params[:credit_card],
      email: params[:email],
    }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!

  def index
    @contacts = current_user.contacts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact_files/index.html.erb
<%= link_to 'Upload a new file', new_contact_file_path %>
</br>
<%= link_to 'All contacts', contacts_path %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Status</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  <tbody>
    <% @contact_files.each do |contact_file| %>
      <tr>
        <th scope="row"><%= contact_file.id %></th>
        <td><%= contact_file.csv_file.name %></td>
        <td><%= contact_file.status %></td>
        <td><%= contact_file.created_at.strftime('%Y %B %-d') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contact_files/new.html.erb
<%= form_with model: @contact_file, class: "nifty_form" do |f| %>
  <div class="form-group">
    <label for="contact_file_csv_file">CSV file</label>
    <%= f.file_field :csv_file, class: 'form-control-file' %>
  </div>

  <div class="form-group">
    <label>Name</label>

    <select name="name" id="name">
    </select>
  </div>

  <div class="form-group">
    <label>Birthday</label>

    <select name="birthday" id="birthday">
    </select>
  </div>

  <div class="form-group">
    <label>Phone</label>

    <select name="phone" id="phone">
    </select>
  </div>

  <div class="form-group">
    <label>Address</label>

    <select name="address" id="address">
    </select>
  </div>

  <div class="form-group">
    <label>Credit Card</label>

    <select name="credit_card" id="credit_card">
    </select>
  </div>

  <div class="form-group">
    <label>Email</label>

    <select name="email" id="email">
    </select>
  </div>

  <%= f.submit "Create" %>
<% end %>

app/views/contacts/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Birthday</th>
      <th scope="col">Address</th>
      <th scope="col">Phone</th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <th scope="row"><%= contact.id %></th>
        <td><%= contact.name %></td>
        <td><%= contact.birthday.strftime('%Y %B %-d') %></td>
        <td><%= contact.address %></td>
        <td><%= contact.phone %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KoombeaTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>